use std::fs;

#[test]
fn trace_file_has_version_and_hash_shape() {
    // Assumes demo output exists or is generated by CI steps later.
    // Here we only validate structure if file exists.
    let path = "target/demo_out/trace.json";
    if !std::path::Path::new(path).exists() {
        return;
    }
    let raw = fs::read_to_string(path).expect("read trace.json");
    let v: serde_json::Value = serde_json::from_str(&raw).expect("json parse");
    assert_eq!(v.get("trace_format_version").and_then(|x| x.as_str()), Some("1"));
    let arr = v.get("trace").and_then(|x| x.as_array()).expect("trace array");
    for e in arr {
        let h = e.get("state_hash_sha256").and_then(|x| x.as_str()).expect("hash");
        assert_eq!(h.len(), 64);
        assert!(h.chars().all(|c| c.is_ascii_hexdigit() && c.is_ascii_lowercase() || c.is_ascii_digit()));
    }
}
